### ISSUE TITLE
feat: Support v2 API

### ISSUE THREAD

**Issue by gregor-mueller** [jotaijs/jotai-tanstack-query#20]
When using the V2 API, the `queryClientAtom` can not be set. This is necessary, as the `initialValues` prop has been removed from the `Provider`.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/28727932/211019832-2ed514f8-e1ec-4d61-b47b-c992d811cba8.png">

Maybe it's too early for requesting this though (as V2 is not officially launched).
It could also be an issue on jotais end (or just incorrect types as it seems to work if I cast the atom as `any` for testing purposes).

**Comment by dai-shi** [comment]
See #18

https://ci.codesandbox.io/status/jotai-labs/jotai-tanstack-query/pr/18
You can install from the codesandbox build. Find "Local Install Instructions" ☝️
