### ISSUE TITLE
How to use async atom in atomsWithQuery jotai v2?

### ISSUE THREAD

**Issue by devnomic** [jotaijs/jotai-tanstack-query#21]
Now it returns typing error
````
const idAtom = atom(async (get) => {
  await new Promise((resolve) => setTimeout(resolve, 100));
  return 1;
});

// Typing error here because of using async
// I need async to await get id from atom id
const [userAtom] = atomsWithQuery(async (get) => {
  const id = await get(idAtom);
  return {
    queryKey: ["getUser", id],
    queryFn: async () => await fetch("https://reqres.in/api/users/" + id)
  };
});

````

Reproduction link: 
https://codesandbox.io/s/nifty-kirch-sg309h?file=/src/App.tsx

<img width="810" alt="Screen Shot 2023-02-02 at 19 54 48" src="https://user-images.githubusercontent.com/101681592/216330620-a93a5756-7542-491d-b7da-1b674c766ffe.png">

Thank you

**Comment by dai-shi** [comment]
Good question. It's not entirely solved yet.
Related discussion: https://github.com/pmndrs/jotai/discussions/1615
Let me know which solution (more or less workaround) you like.

**Comment by devnomic** [comment]
Thank you for fast reply! 
Improve `jotai-tanstack-query` seems the way jotai users naturally expect when migrate.
I was about to migrate my code to jotai v2.

I tried using `unstable_unwrap` expecting it handle the await for me, but didn't work either.
````
const [usersAtom] = atomsWithQuery((get) => {
  const id = unstable_unwrap(idAtom);
  return {
    queryKey: ["getUsers", id],
    queryFn: async () => await fetch("https://reqres.in/api/users/" + id)
  };
});
````
Using `loadable` seems too verbose.

I will try atoms in atom, and report. seems it will work. I'll report back later.
Hopefully can create general function wrapper such as asyncAtomsWithQuery.

**Comment by dai-shi** [comment]
Currently, my belief is improving `jotai-tanstack-query` is hardly possible or maintainable. (That doesn't stop someone to try and correct me.)

I hope `unwrap` to work. It should return `undefined` initially, so can you try `enabled: id === undefined` and see if it works around?

**Comment by devnomic** [comment]
This one works, i think it fetched twice with `undefined` and `1` as id
````
const [userAtom] = atomsWithQuery((get) => {
  const id = get(unstable_unwrap(idAtom));
  return {
    queryKey: ["getUser", id],
    queryFn: async () => {
      const res = await fetch("https://reqres.in/api/users/" + id);
      return res.json();
    }
    //enabled: id !== undefined
  };
````
https://codesandbox.io/s/summer-dream-gwrv7j?file=/src/App.tsx

Uncommenting the enabled makes it loading forever. So it seems unstable unwrap cannot be used.

**Comment by dai-shi** [comment]
Final resort: https://codesandbox.io/s/brave-voice-ruxvdp

**Comment by devnomic** [comment]
Unfortunately this one seems need extra work to handle the null in the component.
> Final resort: https://codesandbox.io/s/brave-voice-ruxvdp

I tried to wrap the atom query in atom, seems promising but not working, maybe you can have a look.
https://codesandbox.io/s/dawn-currying-0ljnqr?file=/src/App.tsx

**Comment by devnomic** [comment]
Unfortunately this one seems need extra work to handle the null in the component.
> Final resort: https://codesandbox.io/s/brave-voice-ruxvdp

I tried to wrap the atom query in atom, seems promising but not working, maybe you can have a look.
https://codesandbox.io/s/dawn-currying-0ljnqr?file=/src/App.tsx

**Comment by dai-shi** [comment]
Here you go: https://codesandbox.io/s/musing-shirley-fq0p9c

**Comment by dai-shi** [comment]
> Uncommenting the enabled makes it loading forever.

We want to fix this if possible. The tricky part is TanStack Query requires to re-use observer on option change. Hmm, tbh, I'm not sure what's blocking. Can be a bug. Can be a limitation.

**Comment by devnomic** [comment]
> Here you go: https://codesandbox.io/s/musing-shirley-fq0p9c

Thank you! This seems the way to go, but need utils function to wrap the atomsQuery and hooks to get the value since writing double `useAtomValue` seems weird.

**Comment by dai-shi** [comment]
Yeah, a util function would be nice. It can probably avoid dobule useAtomValue. We can consider adding such a util in this lib.

**Comment by devnomic** [comment]
I tried to write a generic utils for this, it seems works fine, but need your help with the typing. Right now i'm using `any`

https://codesandbox.io/s/quirky-farrell-3f9r7j?file=/src/utils.ts

**Comment by devnomic** [comment]
Updated with typing:
https://codesandbox.io/s/broken-bash-wpco26?file=/src/utils.ts

Seems work for async and sync atom now.

Is there a way to get the value using `useAtomValue` instead double `useAtomValue` or it's not possible using atom in atom?

**Comment by dai-shi** [comment]
Ended up with rewriting. Here you go: https://codesandbox.io/s/bold-cherry-o10yl5?file=/src/utils.ts

I found a fix in jotai's type utils. Will open a PR there.

**Comment by devnomic** [comment]
Amazing, as expected from @dai-shi sensei, thank you, it seems i can try migrate my code now.

**Comment by dai-shi** [comment]
> I found a fix in jotai's type utils. Will open a PR there.

https://github.com/pmndrs/jotai/pull/1741

**Comment by dai-shi** [comment]
@devnomic If it goes well, would you open a PR in this repo?

**Comment by devnomic** [comment]
Yes sure

**Comment by mwisnicki** [comment]
> Ended up with rewriting. Here you go: https://codesandbox.io/s/bold-cherry-o10yl5?file=/src/utils.ts
> 
> I found a fix in jotai's type utils. Will open a PR there.

This looks pretty great and solves my usecase. I would love to also see splitAsyncAtom to simplify it :)

**Comment by dai-shi** [comment]
I think splitAtom case is easy. Just `unstable_unwrap` would do. Please check the v2 migration guide.
https://github.com/pmndrs/jotai/blob/11add6285012fed1c9b25928e3d7ade694e3dd00/docs/guides/migrating-to-v2-api.mdx?plain=1#L212

**Comment by mwisnicki** [comment]
Thanks for he pointers.
I tried playing with it and realized my suggestion was not applicable since in this case the function returns array directly and one can't make array out of atom since the size would be unknown until read.
