### ISSUE TITLE
Setting other atoms in mutation callbacks

### ISSUE THREAD

**Issue by carlesba** [jotaijs/jotai-tanstack-query#22]
I see it's not possible to set other atoms from the atomWithMutation one. Is there any conceptual error in this use case?

I find very common to invalidate other query atoms with a mutation is done. Since the invalidation has to be done in atom setters, this is not possible from within an atom and needs to be done in components.

ie:
```ts
const mutation = atomsWithMutation((get, set) => ({ 
    mutationKey: ["key"],
    mutationFn: (variables) => fetcher(variables),
    onSettled() {
	set(invalidateAtom)
    },
  }))
```

**Comment by dai-shi** [comment]
Good point.
By atom design, observer options are declarative and can only have `get`.
Now, as you suggest, mutation callback to have `set` seems valid.

Currently, the limitation is atom model. read function only gets `get`.
In Jotai v2, we have a new feature to overcome this limitation, but it's still new and less stable.

The workaround for now would be combining with a callback atom.

```js
const onSettledAtom = atom({ onSettled: () => { throw new Error('not initialized') } })
const initializeAtom = (null, (get, set) => {
  set(onSettledAtom, { onSettled: () => set(invalidateAtom) })
})
initialzieAtom.onMount = (init) => init()
```

**Comment by carlesba** [comment]
Looks good. Thank you @dai-shi 

I'm planning to upgrade to jotai v2 soon. Is jotai-tanstack-query compatible with v2 already? Could you document how this would look with v2's API?

Thank you again for such a nice library.

**Comment by dai-shi** [comment]
#18 did the migration.
The API follows Jotai v2 API, but the capability is basically the same.
Unless, you used async atoms, see: #21

**Comment by carlesba** [comment]
great! thanks again

**Comment by ahhshm** [comment]
What about `Store`s? They are available outside of React and can be used inside `react-query` callbacks right?
```ts
const mutation = atomsWithMutation((get, set) => ({ 
    mutationFn: (variables) => fetcher(variables),
    onSettled() {
        store.set(anAtom, value)
    },
}))
```

**Comment by dai-shi** [comment]
> What about `Store`s? They are available outside of React and can be used inside mutation callbacks, right?

Yes. tbh, store api is exposed to hack this kind of use cases.

However, in this case, it's not ideal, because an atom shouldn't depend on a specific store. Ideally,atoms should be independent definition, so that they are reusable across multiple stores.

But, if your use case is a single store, why not.

> @dai-shi Is that the "new and less stable" feature that you were talking about?

No, the new feature is called `setSelf`. It's not documented. You can find it somewhere in the source code.
