### ISSUE TITLE
Using atomsWithMutation value triggers suspense

### ISSUE THREAD

**Issue by carlesba** [jotaijs/jotai-tanstack-query#23]
Using the first of the mutation atoms (the one that provides the response) triggers a suspense before the mutation is done. This makes it impossible to use in the same component that triggers the mutation. 

What's the expected way to use it?

```jsx

const [responseAtom, mutationAtom] = atomsWithMutation(config)

function Foo() {
  const mutate = useSetAtom(mutationAtom)
  const response = useValueAtom(responseAtom)
  
  return <div onClick={()=> mutate([{}])}>{response.data}</div>
}

```

Is `responseAtom` supposed to be used only in a different component wrapped into a suspense?

**Comment by dai-shi** [comment]
Yeah, use the second atom.
tbh, I'm not 100% sure about the use case of `atomsWithMutation`.
As nobody developed it, I ended up with something similar to `atomsWithQuery`.
You are welcome to come up with a new solution.
We need contributors.
