### ISSUE TITLE
Is there an easier way to load on click?

### ISSUE THREAD

**Issue by mgeduld** [jotaijs/jotai-tanstack-query#27]
My coworkers and I have been pouring over the docs, trying to figure out how to use atomsWithQuery but to *not* run the query function until the user clicks a button. We got to working, but with what feels like a hack:

```js
const dofetchAtom = atom(false)

const [randomNumberAtom] = atomsWithQuery((get) => {
  const shouldFetch = get(dofetchAtom)

  return ({
    queryKey: ['randomNumber'],
    queryFn: () => {
      return shouldFetch 
        ? Promise.resolve(Math.random())
        : Promise.resolve(null);
    }
  })
})
```

and then, in a component

```js
const [randomNumber, dispatch] = useAtom(randomNumberAtom)

  const [shouldDoFetch, setDoFetch] = useAtom(dofetchAtom)

  useEffect(() => {
    if (shouldDoFetch) {
      dispatch({ type: 'refetch' })
    }
  }, [shouldDoFetch, dispatch])
```

... with a onClick function calling setDoFetch and setting it to true.

**Comment by arjunvegda** [comment]
Thanks for reaching out! 

Do you need it to work with Suspense? 

If not, then we could disable [the query](https://tanstack.com/query/v4/docs/react/guides/disabling-queries) using the query observer result (second atom)
 
See: https://codesandbox.io/s/jotai-tanstack-query-issue-27-6l818t?file=/src/App.tsx

**Comment by mgeduld** [comment]
Yes. I need it to work with Suspense.

**Comment by mgeduld** [comment]
disabling would be perfect if it wasn't for that. But when it's disabled, Suspense thinks it's still loading.

**Comment by arjunvegda** [comment]
Is it possible to do that using `useQuery` directly, do you have an example by any chance?   

@dai-shi - Is that possible?

**Comment by mgeduld** [comment]
Different from the example I posted above? 

I'm not sure how you'd do it with useQuery.

**Comment by arjunvegda** [comment]
Yes! I wonder if this behavior is achievable with vanilla react-query ([useQuery + Suspense](https://tanstack.com/query/v4/docs/react/guides/suspense)) i.e. without Jotai? 🤔

**Comment by carlesba** [comment]
```js
const dofetchAtom = atom(false)

const [randomNumberAtom] = atomsWithQuery((get) => {
  const shouldFetch = get(dofetchAtom)

  return ({
    queryKey: ['randomNumber'],
    queryFn: () => {
      return Promise.resolve(null);
    },
   enabled: shouldFetch // use enabled to pause the query
  })
})
```

This is `react-query` stuff. Jotai allows it too.

**Comment by dai-shi** [comment]
Hi, sorry for the delay.

@carlesba 's solution https://github.com/jotaijs/jotai-tanstack-query/issues/27#issuecomment-1459654797 is the right one. It should work with `statusAtom` (the second one).
AFAIR, I don't think `enabled` works with `dataAtom` (the first atom).
Can anyone try?

If you would like to refresh on click, then atomWithRefresh pattern may work.
https://github.com/pmndrs/jotai/blob/d5d38e585f0f0c165329b406b6d8210faf8b8787/docs/recipes/atom-creators.mdx?plain=1#L160

In any case, the OP's hack is a valid workaround, if Suspense is required.

**Comment by mgeduld** [comment]
Okay, sounds like--as far as anyone here knows--that if Suspense is required, there's no way around the hack. 

It would be great if "enabled: false" didn't trigger Suspense's loading state.

**Comment by dai-shi** [comment]
You can combine two hooks, right?
```js
const combinedAtom = atom((get) => get(enabledAtom) ? get(dataAtom) : null)
```

**Comment by mgeduld** [comment]
How would that help with Suspense?

**Comment by mgeduld** [comment]
USAGE:

    const [triggerableAtom, pullTriggerAtom] = useAtomsWithTriggerableQuery(
        {
        queryKey: ['triggerable'],
        queryFn: () => Promise.resolve("I got triggered!")
        },

        "I haven't beent triggered yet" // <-- nullValue
    )
    const [triggerableValue] = useAtom(triggerableAtom)

    // The definition of useTriggerPuller is below
    const setPullTrigger = useTriggerPuller(triggerableAtom, pullTriggerAtom)
  
    // in the jsx:

    { triggerableValue }
    <button onClick={() => setPullTrigger(true)}>pull the trigger</button>

**Comment by dai-shi** [comment]
> How would that help with Suspense?

`null` doesn't suspend. I thought your requirement is to avoid suspense initially.

**Comment by carlesba** [comment]
There're many misconceptions in that code.

If you tell react-query that the key `['foo']` is resolved with `Promise.resolve('foo')`, react-query won't update the query `['foo']`'s value even if you update the atom inside `atomsWithQuery`. 

That's why you're not getting any updates even when you change the top atom. If you want to change a query to be enabled/disabled, use the `enabled` option (with an atom, if you like) to achieve it **as mentioned in previous comments**.

Here's a working example for your case: https://codesandbox.io/s/hidden-shape-fy8pr7

The main issue in your code example is evaluating the result of `doFetchAtom` at the wrong moment. 
If you move that decision outside of `atomsWithQuery` you'll get it working (check the codesandbox in this comment to see play with it).

This library is just an abstraction of jotai and react-query. We still need to understand the internal perks and flaws of those libraries in order to use this one. Please read the docs.

I hope this solves the issue.

**Comment by mgeduld** [comment]
Ah! This makes sense now. Thanks for your patience.
