### ISSUE TITLE
What's the best way to update the data of a query?

### ISSUE THREAD

**Issue by amirhhashemi** [jotaijs/jotai-tanstack-query#28]
I needed to update the date of a query so I came up with this:
```ts
const [, statusAtom] = atomsWithQuery(/* ... */)

const writableStatusAtom = atomWithDefault((get) => get(statusAtom))

function Component() {
  const [data, setData] = useAtom(writableStatusAtom)
  
  setData(/* new data */)
}
```
But I have two problems with this:
1. For some reason after a while the number of observers becomes zero and the query gets disabled! My guess is that after `atomWithDefault` got the value of `statusAtom` it unsubscribes from the QueryObserver.
2. `setData` doesn't update the query cache. I probably should use `queryClient.setQueryData` but I'm not sure if updates the `statusAtom`.

Is there a better way to do that?

**Comment by dai-shi** [comment]
`queryClient.setQueryData` should be the right solution.

```js
const setQueryDataAtom = atom(null, (get, set, arg) => {
  const queryClient = get(queryClientAtom);
  queryClient.setQueryData(/* ... */);
});
```

We might be able to support an action `{ set: data }` if it is a good use case. (PRs are welcome.)

**Comment by kalijonn** [comment]
closing this as a stale issue. setQueryData should be the right way to do this. If you still have questions or issues, feel free to reopen.
