### ISSUE TITLE
[BUG] `useErrorBoundary` does not work with `atomsWithQuery`

### ISSUE THREAD

**Issue by ahhshm** [jotaijs/jotai-tanstack-query#29]
`statusAtom` doesn't return the error to Error Boundary even though I've set `useErrorBoundary: true` :
```ts
const queryOptions = {
  queryKey: ["key"],
  queryFn: async () => {
    throw new Error("Error");
  },
  useErrorBoundary: true, 
  retry: 0,
};

const [dataAtom, statusAtom] = atomsWithQuery(() => queryOptions);

function JotaiData() {
  const [data] = useAtom(statusAtom);
  return <p>Jotai Data</p>;
}

function QueryData() {
  const { data } = useQuery(queryOptions);
  return <p>Query Data</p>;
}

function App() {
  return (
    <div>
      <ErrorBoundary fallbackRender={() => <p>Jotai Error</p>}>
        <JotaiData />
      </ErrorBoundary>
      <ErrorBoundary fallbackRender={() => <p>Query Error</p>}>
        <QueryData />
      </ErrorBoundary>
    </div>
  );
}
```
I expected this to show:
```
Jotai Error
Query Error
```
But it shows:
```
Jotai Data
Query Error
```
Reproduction: https://github.com/ahhshm/jotai-error-boundary-bug

## Why I didn't use `dataAtom`?
Because it requires Suspense and I don't use it. I usually don't use Error Boundaries neither, but as a good practice I use an Error Boundary to show a fallback for general errors like 500 or network error:
```ts
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      useErrorBoundary: (error) => {
        if (error instanceof AxiosError) {
          return !error?.response?.status || error.response.status >= 500;
        }
        return false;
      },
    },
  },
});
```
That's why I need Error Boundary but not Suspense.

**Comment by dai-shi** [comment]
Nice catch. It's not supported. We should actually omit the type.
It might be possible to support it, but it will make the integration code complex.
(Anyone interested can give a try though.)

I think the workaround is to throw an error on our end:
```js
const [data] = useAtom(statusAtom);
if (data.hasError) throw data.error;
```

something like that.
