### ISSUE TITLE
setQueryData for an inactive query doesn't update its atom state

### ISSUE THREAD

**Issue by dTalion** [jotaijs/jotai-tanstack-query#39]
[Consider example in the sandbox](https://codesandbox.io/s/jotai-tanstack-query-ensure-that-setquerydata-for-an-inactive-query-updates-its-atom-state-f5crg6?file=/src/App.tsx)

Steps to Reproduce:

- Click on "Unmount."
- Click on the "Set user 5" button.
- Click on "Mount."

Desired Outcome:

The user ID 5 should be displayed.

Actual Outcome:

The user ID 1 is displayed.

Additional Information:
After digging into this, I noticed that the query observable gets unsubscribed once the component is unmounted. However, this behaviour is not align with the expectations, as React Query continues to maintain the query for the specified cache time (default is 5 minutes).

https://tanstack.com/query/v4/docs/react/guides/caching

I am considering the following possible solutions:

- Modify the unsubscription behaviour to occur when the cache time expires via a throttle function.
- Ensure that the query is unsubscribed on removed event.

I would appreciate any thoughts or suggestions

**Comment by kalijonn** [comment]
The new implementation fixes this issue. I've added your test from #40 in #56 

Feel free to reopen if the issue still exists.
