### ISSUE TITLE
Idea for overhaul

### ISSUE THREAD

**Issue by dai-shi** [jotaijs/jotai-tanstack-query#42]
I've kept saying in several places that we may need to re-design this library from scratch.
- https://github.com/jotaijs/jotai-tanstack-query/issues/32#issuecomment-1523619697
- https://github.com/jotaijs/jotai-tanstack-query/pull/38#discussion_r1317912221
- https://github.com/jotaijs/jotai-tanstack-query/pull/40#issuecomment-1710943917

---

A bit of context: https://blog.axlight.com/posts/you-might-not-need-react-query-for-jotai/
> I had been struggling with the mismatch, and ended up with creating a new library `jotai-tanstack-query`.

I thought, `const [dataAtom, statusAtom] = atomsWithQuery(...)` was a nice hack, but it's not nice in DX. The library impl is also complicated.

---

The mismatch is still there. We have several issues reported. In fact, `jotai-urql` is overhauled due to the same reason.

So, the general idea is to re-design the binding api fully from the TanStack Query perspective.
I can help from the Jotai perspective, but we need someone with TanStack Query background to maintain this project.

**Comment by cyrilchapon** [comment]
To add some feedback on DX for a newcoming :
- indeed the 2-atoms-returned logic seems strange, and not really aligned with any jotai usual logic
- even more misleading : the fact both atoms are actually writeable atoms, which basically blew my mind (what are the setters actually supposed to do ?)
- The [typing is broken](https://github.com/jotaijs/jotai-tanstack-query/issues/25), and you inevitably encounter this one and have to take 15 minutes to find this issue to get a workaround
- I personally hard tried to go with Suspense and ErrorBoundary (a hacky react-native port of it) without any actual success. Rolled back to the statusAtom
- statusAtom typing is not correctly discriminated (might be a react-query trouble though); such as isSuccess and isError are not discriminating data
