### ISSUE TITLE
Changing queryKey causes an intermediate inconsistent render

### ISSUE THREAD

**Issue by fifv** [jotaijs/jotai-tanstack-query#44]
[Here is the reproduce repo](https://github.com/fifv/issue-jotai-query)

![image](https://github.com/jotaijs/jotai-tanstack-query/assets/75289510/17c89fcd-487f-441e-9fe3-db122dc9db65)

If I change an atom, say `message`, which is depended by queryKey, the component will immediately re-render with new `message`, but the queryStatus returned by atomWithQuery's second result is still `status: success` `data: <oldData>`

After that render, query actually starts and render with `status: pending` `data: undefined` then `status: success` `data: <newData>`

In `react-query`, changing the queryKey will immediately set `status: pending` `data: undefined` as expected.

This intermediate inconsistent render may cause bugs.

jotai was amazing, with thanks!

**Comment by dai-shi** [comment]
That's a support for #42.

cc: @kalijonn

**Comment by kalijonn** [comment]
unable to reproduce this after upgrading to v0.8.0. Feel free to reopen if you're still seeing this.
