### ISSUE TITLE
Typescript infer queryKey to unknown

### ISSUE THREAD

**Issue by Landon-CN** [jotaijs/jotai-tanstack-query#46]
Code at example https://github.com/jotaijs/jotai-tanstack-query/blob/main/examples/01_typescript/src/App.tsx#L10

![image](https://github.com/jotaijs/jotai-tanstack-query/assets/12167648/8ce9510a-832b-41e1-bd26-55267c61c2cf)

correct expect:

id infer to number

**Comment by dai-shi** [comment]
Maybe it's a bug, or a typescript limitation.
A naive workaround: https://tsplay.dev/WPBrqN

**Comment by kalijonn** [comment]
same as this? #25 

explicitly annotating get as Getter kinda works. If I remember correctly it would say string | number rather than unknown.

**Comment by dai-shi** [comment]
Okay, let's close this as duplicate of #25.
