### ISSUE TITLE
React-query v5 OnSuccess, OnError ...

### ISSUE THREAD

**Issue by lveillard** [jotaijs/jotai-tanstack-query#51]
Hello!

When updating to tanstack query v5 there is a relevant breaking change to consider:
https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose

=> onSuccess and the other callbacks will not be available.

In our case, we are currently using the onSuccess of a atomWithQuery to set another atom, something like this:

```
 const loadAndCacheUnitAtom = atom(null, async (get, set, { unitId, onSuccess }) => {
	
       const [loadUnitAtomTwo] = atomsWithQuery((g) => {

		return {
			queryKey: ['units', unitId],
			queryFn: async () => query(spaceId, payload),
			onSuccess: (data: any) => {
				if (onSuccess) {
					const { units } = data;
					set(setUnitsMapAtom, units);
				}
			},
		};
	});
	return get(loadUnitAtomTwo);
});

```

the ugly alternative for this in react query when you really need to sync your store is to use useEffect:
![image](https://github.com/jotaijs/jotai-tanstack-query/assets/29461076/6497d3dd-dfca-49da-914b-3916f9820ae8)

How can we get the same result here and properly do a set to another atom on query sucess?

Thanks!

**Comment by dai-shi** [comment]
Related: #42 
WIP: #45 

You are welcome to join this effort.

**Comment by kalijonn** [comment]
This issue is stale. API has been changed to be closer to React Query.

To answer the question about setting, you should derive the atom rather than setting onSuccess.
