### ISSUE TITLE
TypeError: Cannot destructure property

### ISSUE THREAD

**Issue by nonishant** [jotaijs/jotai-tanstack-query#52]
Hi there, I've encountered a peculiar bug that has hindered my development progress.

I'm utilizing `jotai-tanstack-query` within my `NEXTJS` production code. Initially, everything worked smoothly in multiple projects where I used it. However, I've recently encountered issues with calling `atomsWithMutation`. Strangely, no changes were made to package versions or peer dependencies.

> Error
TypeError: Cannot destructure property 'email' of 'param' as it is undefined.
    at Object.mutationFn (auth.atom.ts:223:21)
    at Object.fn (mutation.mjs:87:1)
    at run (retryer.mjs:101:1)
    at createRetryer (retryer.mjs:149:1)
    at executeMutation (mutation.mjs:81:35)
    at Mutation.execute (mutation.mjs:138:1)

To elaborate on the issue:

I wrapped my app with Jotai and Tanstack providers in `_app.tsx`:

```tsx


import {ProgressBar} from '@components/ProgressBar';
import {config} from '@fortawesome/fontawesome-svg-core';
import {AdminLayout} from '@layout';
import {Hydrate, QueryClient, QueryClientProvider} from '@tanstack/react-query';
import {ReactQueryDevtools} from '@tanstack/react-query-devtools';
import {Provider} from 'jotai';
import {useHydrateAtoms} from 'jotai/react/utils';
import {queryClientAtom} from 'jotai-tanstack-query';
import type {AppProps} from 'next/app';
import Head from 'next/head';
import {useRouter} from 'next/router';
import React from 'react';
import {ToastContainer} from 'react-toastify';
import {appStore} from 'src/api/atoms/app.atom';

import ErrorBoundary from './errorboundary';



config.autoAddCss = false;
const queryClient = new QueryClient({
	defaultOptions: {
	  queries: {
			staleTime: Infinity,
	  },
	},
});

// @ts-expect-error we don't know the type yet for the children
const HydrateAtoms = ({children}) => {
	useHydrateAtoms([[queryClientAtom, queryClient]]);
	// eslint-disable-next-line @typescript-eslint/no-unsafe-return
	return children;
};

function MyApp({Component, pageProps}: AppProps) {
	const router = useRouter();




	return (
		<>
			<Head>
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<ErrorBoundary>
				{/* Provider to use the useQuery and useMutation */}
				<QueryClientProvider client={queryClient}>
					{/* React Query client's hydration state */}
					<Hydrate state={pageProps.dehydratedState as unknown}>

						<Provider store={appStore}>
							{/*
This Provider initialisation step is needed so that we reference the same
queryClient in both atomWithQuery and other parts of the app. Without this,
our useQueryClient() hook will return a different QueryClient object
*/}
							<HydrateAtoms>
								<ProgressBar />
								{/* lets decide and fix one of these */}
								
								<ToastContainer position="bottom-center"  hideProgressBar autoClose={2000}
								/>
										<Component {...pageProps} />
							</HydrateAtoms>
						</Provider>
					</Hydrate>
					{/* This dev tool doesn't seem to work as of now */}
					<ReactQueryDevtools />
				</QueryClientProvider>
			</ErrorBoundary></>
	);
}

export default MyApp; 
```

I have an atoms file located at `/src/api/atoms/auth.atoms.ts` :

```ts
export const [, loginAtom] = atomsWithMutation(() => ({
  mutationKey: ['login'],
  mutationFn: async ({email, password}: ILoginPayload) =>
    postApiWithAuth('/Security/Login', {email, password}),
  onSuccess(res) {
    formatAndDisplay(res!, 'OTP sent to registered email!');
  },
  onError(err) {
    formatAndDisplay(err as string, 'err'); 
  },
}))
```

While I call the atom in my UI component  

```tsx
const [, postLogin] = useAtom(loginAtom);

const login = async (e: {preventDefault: () => void}) => {		 
		// We can use toast.loading and update with the combination of it
		e.preventDefault();
		await postLogin([
			{
				email: username,
				password,
			},
		]).then(async res => {
			if (!isErrorInAPI(res!)) {
				setIsButtonDisabled(true);
				setUserEmailAtom(username);
				setModal(false);
				setPassHashGen(encryptValue(password));
				await routeToOTP();
			}
		}).catch(err => {
			formatAndDisplay(err as string);
		});
		
	};

```
And the thing that surprises me is this is only happening in devices with Windows OS, and the email and password is being passed everytime.

I am attaching package.json of one of my project for dependencies:

[package (2).json](https://github.com/jotaijs/jotai-tanstack-query/files/13277012/package.2.json)

This has started to appear since last week and it is occurring in almost all of my projects, any help will be really appreciated.

EDIT: Now I am getting this on macOS too.

**Comment by kalijonn** [comment]
Can you help with a minimal repro?

**Comment by nonishant** [comment]
> Can you help with a minimal repro?

The code is bit on the heavier side, wherein I have too many components wrapped up, what I have provided as of now is the minimal setup which had me the issue in first run, what I can do Is provide you the package.lock.json file which has the peer dependencies in it.
If anything seems suspicious there do let me know.
[package-lock.json](https://github.com/jotaijs/jotai-tanstack-query/files/13841920/package-lock.json)

**Comment by kalijonn** [comment]
kind of a long shot but it might be related to @tanstack/query-core's version. jotai-tanstack-query taps into @tanstack/query-core rather than any framework specific bindings like @tanstack/react-query or @tanstack/vue-query.

When you only install jotai-tanstack-query and not query-core, it installs the most recent version which is v5.

To solve this, you can just install @tanstack/query-core@<whatever version your react-query package is>

**Comment by nonishant** [comment]
closing this issue, the problem was with package installer.
My experience with `pnpm` has been bad.
