### ISSUE TITLE
TypeError: No overload matches this call

### ISSUE THREAD

**Issue by HarlamovEvgeniy** [jotaijs/jotai-tanstack-query#61]
When using the example from the documentation: https://jotai.org/docs/extensions/query. 
I'm getting an error:

_No overload matches this call.
  The last overload gave the following error.
    Argument of type 'Atom<InfiniteQueryObserverResult<InfiniteData<any, unknown>, Error>>' is not assignable to parameter of type 'Atom<any>'.
      Types of property 'read' are incompatible.
        Type 'Read<InfiniteQueryObserverResult<InfiniteData<any, unknown>, Error>, never>' is not assignable to type 'Read<any>'.
          Target signature provides too few arguments. Expected 2 or more, but got 1._
          
**Here is my sample code:**
```
const postsAtom = atomWithInfiniteQuery(() => ({
	queryKey: ['posts'],
	queryFn: async ({ pageParam }) => {
		const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_page=${pageParam}`)
		return res.json()
	},
	getNextPageParam: (lastPage, allPages, lastPageParam) => lastPageParam + 1,
	initialPageParam: 1,
}))
```

```
const [{ data, fetchNextPage, isPending, isError, isFetching }] =
    useAtom(postsAtom) // The error appears here
```

Versions:
"jotai": "^1.9.0",
"jotai-tanstack-query": "^0.8.1",
"typescript": "^4.4.2",
"react": "^18.2.0",

**Comment by kalijonn** [comment]
Looks like jotai v1 vs v2 issue. At the moment, jotai-tanstack-query only supports jotai v2.

**Comment by dai-shi** [comment]
@kalijonn we also want to update peer dependency version. "jotai>=2.0.0"

**Comment by kalijonn** [comment]
updated peer dependency.
