### ISSUE TITLE
Type issue in atomWithMutation

### ISSUE THREAD

**Issue by mrodyhin** [jotaijs/jotai-tanstack-query#63]
When using `atomWithMutation`, type of `mutateAsync` resolves to `any`:

[live example](https://codesandbox.io/p/sandbox/jotai-atomwithquery-demo-forked-cm9mww?file=%2Fsrc%2FApp.tsx%3A27%2C11-27%2C22)
<img width="820" alt="image" src="https://github.com/jotaijs/jotai-tanstack-query/assets/11924548/e2ddb799-ac9e-4501-9d2e-b35f53ac5d5c">

I found that in `/dist/src/atomWithMutation.d.ts` it tries to import that type from the file that doesn't exist:
<img width="1734" alt="image" src="https://github.com/jotaijs/jotai-tanstack-query/assets/11924548/63421fc1-1e75-4208-8a91-5565372a506c">

**Comment by kalijonn** [comment]
fixed in #66
