### ISSUE TITLE
atomWithSuspenseQuery don't support enabled

### ISSUE THREAD

**Issue by alexshelkov** [jotaijs/jotai-tanstack-query#64]
`atomWithSuspenseQuery` don't support the `enabled` option. It always call the `queryFn` even if `enabled` set to `false`.

**Comment by kalijonn** [comment]
atomWithSuspenseQuery works the same as useSuspenseQuery which doesn't support 'enabled'. ref: https://tanstack.com/query/v5/docs/react/guides/suspense
