### ISSUE TITLE
unknown type for unified dataAtom

### ISSUE THREAD

**Issue by dingzhou6** [jotaijs/jotai-tanstack-query#69]
<img width="340" alt="Screenshot 2024-02-02 at 5 19 51 PM" src="https://github.com/jotaijs/jotai-tanstack-query/assets/27805592/afe91036-44c9-4f9e-8b1a-75b679ce2612">

should this [type](https://github.com/jotaijs/jotai-tanstack-query/blob/main/src/types.ts) to be included in built ? im getting unknown type for the unified dataAtom

version: v0.8.4

**Comment by kalijonn** [comment]
I don't understand the context. Can you elaborate on code sample, maybe a minimal repro? What atom are you using? is this for every usage of it, or some edge case like an async dependency or something?

**Comment by dingzhou6** [comment]
example https://replit.com/@chiadingzhou/sample#src/App.tsx

when you hover to `data` or `isPending`, it does not suggest the correct type

**Comment by dingzhou6** [comment]
resolved in 0.8.5
