### ISSUE TITLE
V0.8.1 breaks tests that use `atomWithSuspenseQuery` and MSW 1.3.2

### ISSUE THREAD

**Issue by wcardosodev** [jotaijs/jotai-tanstack-query#71]
Hey guys after bumping to use `v0.8.1` some of our tests don't seem to work while using `atomWithSupenseQuery` from jotai (2.6.0) and `server` from `msw` (1.3.2) to mock our api calls. This is a test we have:
```
  it('when has no data show fallback message', async () => {
    server.use(rest.get(`http://api/events`, (req, res, ctx) => res(ctx.json([]))));

    renderWithProviders(<Component />);

    expect(await screen.findByText("title")).toBeInTheDocument();
    expect(await screen.findByText("description")).toBeInTheDocument();
  });
```
As of bumping from `0.8.0` to `0.8.1` this test no longer works as the `server.use` override no longer gets called and the test renders the component with old data from the other previous tests

**Comment by kalijonn** [comment]
I don't think I can troubleshoot from this snippet. Would you be able to create a minimal repro?

**Comment by wcardosodev** [comment]
@kalijonn apologies, have spent some more time on this and it was an issue with our cache setup.
