### ISSUE TITLE
atomWithSuspenseQuery execute the query even if `enabled` is false

### ISSUE THREAD

**Issue by drodrigue-solace** [jotaijs/jotai-tanstack-query#74]
When using `atomWithSuspenseQuery()` with a `false` for the `enabled` option, the query is executed anyway. It should be executed only if the enabled option is true.

e.g.
```
const enabledAtom = atom(false);
const queryAtom = atomWithSuspenseQuery((get) => ({
	queryKey: ["my-key"],
	queryFn: () => fetch("the-url"),
	enabled: get(enabledAtom)
}));
```

I would have expected that the query stay pending until the `enabledAtom` is set to `true` in the example above.

Tested with:
- react 17.0.2
- jotai 2.7.0
- jotai-tanstack-query 0.8.5
- @tanstack/query-core: 4.36.1
- @tanstack/react-query: 4.36.1

**Comment by kalijonn** [comment]
v0.8.x only supports react query v5. we're setting enabled to true for all suspense queries to be consistent with react query v5.

**Comment by drodrigue-solace** [comment]
I can understand that if `enabled` is not specified, the code can set it to true, but it seems I still should be able to control that somehow. Obviously I don't know all the internal details and behaviours of react-query.

**Comment by drodrigue-solace** [comment]
Closing issue
