### ISSUE TITLE
[atomWithSuspenseQuery]: placeholderData prop is not working

### ISSUE THREAD

**Issue by hermantolim** [jotaijs/jotai-tanstack-query#76]
in React Query we can keep previous data for pagination, as can be seen in the [documentation](https://tanstack.com/query/latest/docs/framework/react/guides/paginated-queries)

but the `placeholderData` prop is not use by `atomWithSuspenseQuery`, this cause re-fetching data from previous page when the page atom is updated

```
jotai: ^2.7.0
jotai-tanstack-query: ^0.8.5
```

**Comment by grzesiek-ds** [comment]
`placeholderData` has been removed from `useSuspenseQuery`, therefore it has been removed from `atomWithSuspenseQuery`.

https://tanstack.com/query/latest/docs/framework/react/reference/useSuspenseQuery

![image](https://github.com/jotaijs/jotai-tanstack-query/assets/95348943/cd058328-389e-4cee-80e6-c4fa398fbe23)

**Comment by hermantolim** [comment]
closing this issue, thanks for the info
