### ISSUE TITLE
Not showing in @tanstack/react-query-devtools

### ISSUE THREAD

**Issue by hermantolim** [jotaijs/jotai-tanstack-query#77]
I followed the [documentation](https://jotai.org/docs/extensions/query) but query made by this lib is not showing in the devtools, while the query made without this lib showed

```
@tanstack/react-query-devtools: 5.28.4
jotai: 2.7.0
jotai-tanstack-query: 0.8.5
@tanstack/query-core: 5.28.4
@tanstack/react-query: 5.28.4
```

**Comment by kalijonn** [comment]
You need to ensure that the DevTools and Jotai are referencing the same queryClient. I can take a look if it isn't working.

example: https://codesandbox.io/p/sandbox/jotai-query-devtools-zlp3pj

**Comment by hermantolim** [comment]
sorry, i thought hydrate atom is only for SSR, it turns out you need it too
