### ISSUE TITLE
Why make wonka as peerDenpendency?

### ISSUE THREAD

**Issue by Mayandev** [jotaijs/jotai-tanstack-query#78]
Dumb question: Why make `wonka` as peerDenpendency?

**Comment by VIKTORVAV99** [comment]
I would consider this blocking for us as we don't use Wonka nor need another framework with it's own set of dependencies we won't use.

I checked the other extensions and only URQL and Query has it as a peer dependency.

Which is very unfortunate as we would have liked to at least explored use cases for this.

**Comment by kalijonn** [comment]
We removed wonka for everything except Mutations. #84 removes it for mutation as well.
