### ISSUE TITLE
Question: Is it OK to map over AtomWithQueryResult?

### ISSUE THREAD

**Issue by emccorson** [jotaijs/jotai-tanstack-query#79]
I couldn't find anywhere else to ask this, so sorry in advance if this is the wrong place.

I'd like to be able to apply a function to the data part of an `AtomWtihQueryResult` value. I have the following implementation, which I think works fine, but are there any reasons I am missing why this would not work or is a bad idea?

```typescript
const mapQueryResult = <A,B,E>(
  f: ((a: A) => B),
  queryResult: AtomWithQueryResult<A, E>
): AtomWithQueryResult<B, E> => {
  if (queryResult.isSuccess || queryResult.isRefetchError) {
    return {
      ...queryResult,
      data: f(queryResult.data),
      refetch: (...args) => queryResult.refetch(...args).then(res => mapQueryResult(f, res))
    };
  } else {
    return queryResult;
  }
};
```

**Comment by kalijonn** [comment]
Nothing is obviously bad to me about that implementation. But if you only want to transform data, you can either use a derived atom, or use the `select` property available in useQuery: https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

**Comment by kalijonn** [comment]
Feel free to reopen or file a new issue.

**Comment by emccorson** [comment]
Thanks! That's very helpful.
