### ISSUE TITLE
Can I use `set` feature on atomWithMutation?

### ISSUE THREAD

**Issue by kbaba1001** [jotaijs/jotai-tanstack-query#81]
Hi, thank you for great library.

I'd like to use `set` feature on `atomWithMutation` like this

```javascript
const signInPostAtom = atomWithMutation((get, set) => ({
	mutationKey: ["sign-in"],
	mutationFn: (data: { email: string; password: string }) => {
		return httpClient().post("users/sign-in", { json: data }).json();
	},
        onSuccess: (res) => {
               set(jwtTokenAtom, res.data.jwtToken)        // I want this !!
        }
}));
```

Currently, since `atomWithMutation` cannot use `set` feature, I use `atomEffect`.
However, `atomEffect` is not only called after request is success. `onSuccess` option is so useful.

Please, consider this feature

**Comment by kalijonn** [comment]
You have 2 options:
1. You can create derived from the mutation atom like `tokenAtom` and use it in `TokenConsumerComponent`
2. You can directly use `signInPostAtom` in the `TokenConsumerComponentV2` which rerenders as the mutation atom's state changes from idle to pending to post api result

```js
const signInPostAtom = atomWithMutation((get) => ({
  mutationKey: ['sign-in'],
  mutationFn: (data: { email: string; password: string }) => {
    return httpClient().post('users/sign-in', { json: data }).json()
  },
}))

const tokenAtom = atom(get => {
  const signInMutationResponse = get(unwrap(signInPostAtom))
  return signInMutationResponse?.data?.jwtToken
})

const TokenConsumerComponent = () => {
  const [token] = useAtom(tokenAtom)
  return <div>{token ?? ""}</div>
}

const TokenConsumerComponentV2 = () => { 
  const [{ data }] = useAtom(signInPostAtom)
  return <div>{data?.data?.jwtToken ?? ""}</div>
}

```

**Comment by peterferguson** [comment]
> You have 2 options:
> 
> 1. You can create derived from the mutation atom like `tokenAtom` and use it in `TokenConsumerComponent`
> 2. You can directly use `signInPostAtom` in the `TokenConsumerComponentV2` which rerenders as the mutation atom's state changes from idle to pending to post api result
> 
> ```js
> const signInPostAtom = atomWithMutation((get) => ({
>   mutationKey: ['sign-in'],
>   mutationFn: (data: { email: string; password: string }) => {
>     return httpClient().post('users/sign-in', { json: data }).json()
>   },
> }))
> 
> const tokenAtom = atom(get => {
>   const signInMutationResponse = get(unwrap(signInPostAtom))
>   return signInMutationResponse?.data?.jwtToken
> })
> 
> const TokenConsumerComponent = () => {
>   const [token] = useAtom(tokenAtom)
>   return <div>{token ?? ""}</div>
> }
> 
> const TokenConsumerComponentV2 = () => { 
>   const [{ data }] = useAtom(signInPostAtom)
>   return <div>{data?.data?.jwtToken ?? ""}</div>
> }
> ```

Neither of these address the issue.

There is still no way to set another atom within the mutation itself or on its callbacks. 

Not having this feature means you cannot colocate side effects of a mutation (that may need to happen every time) that need to update state with the mutation.

This seems antithetical to the structure of mutations in `tanstack-query`

**Comment by kalijonn** [comment]
I don't think this has to be built into jotai-tanstack-query.

1. jotai-effect already lets you set atoms that are not tanstack atoms. You can check if the status is sucess and only then set tokenAtom.
2. tanstack lets you setQueryData when working with optimistic updates.
3. deriving is another option.

Let me know if I'm missing something. I'm closing this issue but feel free to re-open if needed.

**Comment by jenseralmeida** [comment]
All those options enable the side effects, but it could be a lot simpler if the set could be used on the mutation.
