### ISSUE TITLE
`atomWithMutationState` Is Broken

### ISSUE THREAD

**Issue by peterferguson** [jotaijs/jotai-tanstack-query#88]
The [docs](https://jotai.org/docs/extensions/query#atomwithmutationstate-usage) state that `atomWithMutationState` gives access to all mutations.

This is not true because there is an explicit override that it only returns pending mutations from the cache.

> [atomWithMutationState usage](https://jotai.org/docs/extensions/query#atomwithmutationstate-usage)
atomWithMutationState creates a new atom that gives you access to all mutations in the [MutationCache](https://tanstack.com/query/v5/docs/react/reference/useMutationState).

https://github.com/jotaijs/jotai-tanstack-query/blob/4bd54751411d60649fb70d4cb09f07ea4246c3a1/src/atomWithMutationState.ts#L24

# Problem

Seems like this was a **bad copy and paste** from the [`useMutationState`](
https://github.com/TanStack/query/blob/59a6d3df3035d6effeaed884f4575b1a0ef8e788/packages/react-query/src/useMutationState.ts) hook file.

The `getResult` code seems to have been mixed with the `useIsMutating` hook which doesn't make sense.

## Tanstacks Code

```ts
function getResult<TResult = MutationState>(
  mutationCache: MutationCache,
  options: MutationStateOptions<TResult>,
): Array<TResult> {
  return mutationCache
    .findAll(options.filters)
    .map(
      (mutation): TResult =>
        (options.select ? options.select(mutation) : mutation.state) as TResult,
    )
}

export function useIsMutating(
  filters?: MutationFilters,
  queryClient?: QueryClient,
): number {
  const client = useQueryClient(queryClient)
  return useMutationState(
    { filters: { ...filters, status: 'pending' } },
    client,
  ).length
}
```

**Comment by kalijonn** [comment]
I added another test in your PR and merged it. I think it was a case of bad copy paste. Thanks for this. I'm looking at your other PRs. Will get to them tomorrow (late in my timezone).
