### ISSUE TITLE
`atomWithQuery` - React Component unmount leads to refetch when the last fetch was unsuccessful

### ISSUE THREAD

**Issue by PetroTsapei** [jotaijs/jotai-tanstack-query#92]
The code below creates additional fetches for failed endpoints when the component unmounts.

The default situation:
- atom created with  `atomWithQuery` used in some `Component`
- `Component` is mounted and fetch is executed with a failed result
- `Component` gets unmounted (for example route change) and jotai unmount together with tanstack reset is executed
- the query is still active and it will be refetched 

<img width="668" alt="image" src="https://github.com/user-attachments/assets/2b49cb75-8ed7-49e0-bb3a-164187aba6e2">

@kalijonn please let me know how I can help to solve this as soon as possible. Is there a way how to disable such behaviour?

**Comment by kalijonn** [comment]
fixed in #93. v0.8.8 released.
